baseURL = "https://your-site-name.netlify.app/"
languageCode = "en-us"
title = "Green Orbit Handbook"
theme = ""  # Leave empty when using modules
enableGitInfo = true
enableRobotsTXT = true
paginate = 10
canonifyURLs = true

# Output formats
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Language settings
[params]
  description = "Sustainable marketing handbook for space and beyond"
  author = "Green Orbit Digital"
  github_repo = "https://github.com/greenorbitspace/greenorbit-handbook"
  showBreadcrumbs = true
  showReadingTime = true

# Enable features in Docsy
[params.ui]
  sidebar_menu_compact = true
  sidebar_menu_foldable = true
  sidebar_search_disable = false
  navbar_logo = true

# Google Analytics and other integrations
#[params.analytics]
#  google = "UA-XXXXXX-X"

# Enable syntax highlighting
[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"

# Hugo Modules
[module]
  proxy = "direct"

[[module.imports]]
  path = "github.com/google/docsy"

[[module.imports]]
  path = "github.com/google/docsy/dependencies"

# Menu configuration (customise as needed)
[menu]
  [[menu.main]]
    identifier = "handbook"
    name = "Handbook"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2