# Netlify build configuration for Green Orbit Handbook

[build]
  # Directory to publish after build (should match Hugo's publishDir)
  publish = "public"

  # Build command: tidy Hugo modules, install npm deps, then build production assets & site
  command = "hugo mod tidy && npm install && npm run build:production"

[build.environment]
  HUGO_VERSION = "0.147.8"
  GO_VERSION = "1.20"
  HUGO_ENV = "production"
  NODE_VERSION = "20"
  HUGO_EXTENDED = "true"

# Production-specific environment variables
[context.production.environment]
  HUGO_ENABLEGITINFO = "true"

# Preview deploy context - build drafts and future posts, for previewing unpublished content
[context.deploy-preview]
  command = "hugo mod tidy && npm install && npm run build:preview"
  environment = { HUGO_ENV = "development" }

# Branch deploy context - build site normally with base URL set to deploy preview URL
[context.branch-deploy]
  command = "hugo mod tidy && npm install && npm run build:production"
  environment = { HUGO_ENV = "production" }